{{- if and (.Values.grafanaApiSecret.enabled) (not .Values.grafanaApiSecret.secretKeyReference) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cole.fullname" . }}-grafana-api
  {{- with .Values.grafanaApiSecret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.grafanaApiSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  grafana-api.yaml: |-
    address: {{ .Values.grafanaApiSecret.data.address | quote }}
    apiKey: {{ .Values.grafanaApiSecret.data.apiKey | quote }}
{{- end -}}
